/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.Dialog;

/**
 *
 * @author nguye
 * 
 */
import javax.swing.JTable;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import java.awt.BorderLayout;
import DTO.PhieuNhapDTO;
import BUS.PhieuNhapBUS;
import javax.swing.*;
import DTO.ChiTietPhieuNhapDTO;
import BUS.ChiTietPhieuNhapBUS;
import java.util.List;

// iText classes
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.Phrase;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.io.File;
import java.awt.Desktop;
import java.io.IOException;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;






// Java I/O
import java.io.FileOutputStream;
import java.io.FileNotFoundException;

public class ChiTietPhieuNhapDialog extends javax.swing.JDialog {
      private String maPhieuNhap;  
    private DefaultTableModel model;

    /**
     * Creates new form ChiTietpn
     */
    public ChiTietPhieuNhapDialog(java.awt.Frame parent, boolean modal,String maPhieuNhap) {
   
        super(parent, modal);
        initComponents();
        this.maPhieuNhap=maPhieuNhap;
         hienThiBangPhieuNhap();
        hienThiThongTinPhieuNhap();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btn_inpdf = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        text_maphieunhap = new javax.swing.JTextField();
        text_nhanviennhap = new javax.swing.JTextField();
        text_nhacungcap = new javax.swing.JTextField();
        text_thoigiantao = new javax.swing.JTextField();
        text_tongtien = new javax.swing.JTextField();
        paneltest = new javax.swing.JPanel();
        panel1 = new java.awt.Panel();
        jLabel7 = new javax.swing.JLabel();
        table_phieunhap = new java.awt.Panel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("CHI TIẾT PHIẾU NHẬP");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(jLabel1)
                .addContainerGap(352, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(39, 39, 39))
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 200, 20));

        btn_inpdf.setBackground(new java.awt.Color(0, 204, 204));
        btn_inpdf.setText("IN PDF");
        btn_inpdf.setPreferredSize(new java.awt.Dimension(90, 30));
        btn_inpdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inpdfActionPerformed(evt);
            }
        });
        jPanel4.add(btn_inpdf);

        btn_cancel.setBackground(new java.awt.Color(255, 102, 102));
        btn_cancel.setText("HỦY");
        btn_cancel.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel4.add(btn_cancel);

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel6.setPreferredSize(new java.awt.Dimension(864, 50));
        jPanel6.setLayout(new java.awt.GridLayout(2, 0, 30, 0));

        jLabel2.setText("MÃ PHIẾU NHẬP");
        jPanel6.add(jLabel2);

        jLabel3.setText("NHÂN VIÊN NHẬP");
        jPanel6.add(jLabel3);

        jLabel4.setText("NHÀ CUNG CẤP");
        jPanel6.add(jLabel4);

        jLabel5.setText("THỜI GIAN TẠO");
        jPanel6.add(jLabel5);

        jLabel6.setText("TỔNG TIỀN");
        jPanel6.add(jLabel6);
        jPanel6.add(text_maphieunhap);
        jPanel6.add(text_nhanviennhap);
        jPanel6.add(text_nhacungcap);
        jPanel6.add(text_thoigiantao);
        jPanel6.add(text_tongtien);

        jPanel5.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        paneltest.setLayout(new java.awt.BorderLayout());

        panel1.setMaximumSize(new java.awt.Dimension(0, 30));
        panel1.setPreferredSize(new java.awt.Dimension(864, 30));
        panel1.setLayout(new javax.swing.BoxLayout(panel1, javax.swing.BoxLayout.LINE_AXIS));
        panel1.add(jLabel7);

        paneltest.add(panel1, java.awt.BorderLayout.PAGE_START);

        table_phieunhap.setPreferredSize(new java.awt.Dimension(864, 200));

        javax.swing.GroupLayout table_phieunhapLayout = new javax.swing.GroupLayout(table_phieunhap);
        table_phieunhap.setLayout(table_phieunhapLayout);
        table_phieunhapLayout.setHorizontalGroup(
            table_phieunhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 864, Short.MAX_VALUE)
        );
        table_phieunhapLayout.setVerticalGroup(
            table_phieunhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        paneltest.add(table_phieunhap, java.awt.BorderLayout.CENTER);

        jPanel5.add(paneltest, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_inpdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inpdfActionPerformed
        // TODO add your handling code here:
       
      JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Chọn nơi lưu file PDF");
    fileChooser.setSelectedFile(new File("phieu_nhap.pdf"));

    int userSelection = fileChooser.showSaveDialog(this);
    if (userSelection == JFileChooser.APPROVE_OPTION) {
        File fileToSave = fileChooser.getSelectedFile();

        try {
            // Tải font tùy chỉnh nếu có
            String fontPath = "src/font/DejaVuSans.ttf";
            BaseFont baseFont = BaseFont.createFont(fontPath, BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
            Font font = new Font(baseFont, 12);

            Document document = new Document(PageSize.A4);
            PdfWriter.getInstance(document, new FileOutputStream(fileToSave));
            document.open();
            Paragraph timePrint = new Paragraph("Thời gian in phiếu: 07/10/2023 09:24", font);
            timePrint.setAlignment(Element.ALIGN_RIGHT);     // Căn phải
            timePrint.setSpacingAfter(10f);                  // Khoảng cách phía dưới (nếu cần)
            document.add(timePrint);

   
            // Tiêu đề "THÔNG TIN PHIẾU NHẬP"
           Font titleFont = new Font(baseFont, 18, Font.BOLD); // Cỡ 18, in đậm
            Paragraph title = new Paragraph("THÔNG TIN PHIẾU NHẬP", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            title.setSpacingAfter(20);
            document.add(title);

            // Thông tin chung
            document.add(new Paragraph("Mã phiếu: PN-15", font));
            document.add(new Paragraph("Nhà cung cấp: Công ty Oppo Việt Nam", font));
            
            document.add(new Paragraph("Thời gian nhập: 15/04/2023 00:59", font));
            document.add(new Paragraph("Người thực hiện: Trần Nhật Sinh - Mã nhân viên: 1", font));
            document.add(new Paragraph("\n")); // Xuống một dòng


            // Tạo bảng cho sản phẩm
            PdfPTable table = new PdfPTable(5); // 5 cột: Tên sản phẩm, Phiên bản, Giá, Số lượng, Tổng tiền
            table.setWidthPercentage(100);

            // Thiết lập các tiêu đề cột
            table.addCell(new PdfPCell(new Phrase("Tên sản phẩm", font)));
            table.addCell(new PdfPCell(new Phrase("Phiên bản", font)));
            table.addCell(new PdfPCell(new Phrase("Giá", font)));
            table.addCell(new PdfPCell(new Phrase("Số lượng", font)));
            table.addCell(new PdfPCell(new Phrase("Tổng tiền", font)));

            // Thêm dữ liệu vào bảng
            table.addCell(new PdfPCell(new Phrase("OPPO Reno6 Pro 5G", font)));
            table.addCell(new PdfPCell(new Phrase("256GB - 8GB - Xanh", font)));
            table.addCell(new PdfPCell(new Phrase("12.000.000đ", font)));
            table.addCell(new PdfPCell(new Phrase("13", font)));
            table.addCell(new PdfPCell(new Phrase("156.000.000đ", font)));

            table.addCell(new PdfPCell(new Phrase("OPPO A95", font)));
            table.addCell(new PdfPCell(new Phrase("128GB - 8GB - Bạc", font)));
            table.addCell(new PdfPCell(new Phrase("4.500.000đ", font)));
            table.addCell(new PdfPCell(new Phrase("7", font)));
            table.addCell(new PdfPCell(new Phrase("31.500.000đ", font)));

            document.add(table);

            // Tổng tiền
            document.add(new Paragraph("Tổng thành tiền: 187.500.000đ", font));
            document.add(new Paragraph("\n")); // Xuống một dòng

            // Chữ ký người lập phiếu, nhân viên nhận, nhà cung cấp
            PdfPTable signatureTable = new PdfPTable(3); // 3 cột cho 3 phần chữ ký
            signatureTable.setWidthPercentage(100);

            // Tạo từng ô không có viền
            PdfPCell cell1 = new PdfPCell(new Phrase("Người lập phiếu\n(Ký và ghi rõ họ tên)", font));
            PdfPCell cell2 = new PdfPCell(new Phrase("Nhân viên nhận\n(Ký và ghi rõ họ tên)", font));
            PdfPCell cell3 = new PdfPCell(new Phrase("Nhà cung cấp\n(Ký và ghi rõ họ tên)", font));

            // Xóa viền
            cell1.setBorder(PdfPCell.NO_BORDER);
            cell2.setBorder(PdfPCell.NO_BORDER);
            cell3.setBorder(PdfPCell.NO_BORDER);

            // Căn giữa nội dung
            cell1.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell2.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell3.setHorizontalAlignment(Element.ALIGN_CENTER);

            // Thêm ô vào bảng
            signatureTable.addCell(cell1);
            signatureTable.addCell(cell2);
            signatureTable.addCell(cell3);

            document.add(signatureTable);


            document.close();

            // Mở file PDF sau khi in
            if (Desktop.isDesktopSupported()) {
                Desktop.getDesktop().open(fileToSave);
            }

        } catch (DocumentException | IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi xuất PDF: " + ex.getMessage());
        }
    }
        
        
        
        
        
        
    }//GEN-LAST:event_btn_inpdfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiTietPhieuNhapDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiTietPhieuNhapDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiTietPhieuNhapDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiTietPhieuNhapDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String mapn="test";
                ChiTietPhieuNhapDialog dialog = new ChiTietPhieuNhapDialog(new javax.swing.JFrame(), true,mapn);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

     
    public void hienThiThongTinPhieuNhap(){
        // Lấy thông tin phiếu nhập từ BLL
        PhieuNhapDTO pn=new PhieuNhapDTO();
        PhieuNhapBUS pnbll=new PhieuNhapBUS();
         pn = pnbll.findphieunhapfrommapn(this.maPhieuNhap);

        // Hiển thị thông tin phiếu nhập lên các TextField
        if (pn != null) {
            text_maphieunhap.setText(pn.getMaPhieuNhap());
            text_thoigiantao.setText(pn.getNgayNhap().toString());
            text_nhacungcap.setText(pn.getMaNCC());
            text_nhanviennhap.setText(pn.getMaNhanVien());

        }

    }

public void hienThiBangPhieuNhap() {
    String[] columnNames = {"Mã quạt", "Số lượng", "Đơn giá", "Thành tiền"};

    // Lấy dữ liệu từ BLL
    List<ChiTietPhieuNhapDTO> dsCTPN = ChiTietPhieuNhapBUS.getChiTietPhieuNhapByMaPN(this.maPhieuNhap);

    // Chuyển sang Object[][]
    Object[][] data = new Object[dsCTPN.size()][4];
    for (int i = 0; i < dsCTPN.size(); i++) {
        ChiTietPhieuNhapDTO ct = dsCTPN.get(i);
        data[i][0] = ct.getMaQuat();
        data[i][1] = ct.getSoLuong();
        data[i][2] = ct.getDonGia();
        data[i][3] = ct.getThanhTien();
    }

    // Tạo model và bảng
    model = new DefaultTableModel(data, columnNames);
    JTable table = new JTable(model);

    // Cho bảng vào JScrollPane
    JScrollPane scrollPane = new JScrollPane(table);

    // Hiển thị vào panel
    paneltest.removeAll();
    paneltest.setLayout(new BorderLayout());
    paneltest.add(scrollPane, BorderLayout.CENTER);
    paneltest.revalidate();
    paneltest.repaint();
}

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_inpdf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private java.awt.Panel panel1;
    private javax.swing.JPanel paneltest;
    private java.awt.Panel table_phieunhap;
    private javax.swing.JTextField text_maphieunhap;
    private javax.swing.JTextField text_nhacungcap;
    private javax.swing.JTextField text_nhanviennhap;
    private javax.swing.JTextField text_thoigiantao;
    private javax.swing.JTextField text_tongtien;
    // End of variables declaration//GEN-END:variables
}
